### ISSUE TITLE
Python 3.7 MPF 0.52.0 namedtuple() got an unexpected keyword argument 'verbose'

### ISSUE THREAD

**Issue by muffler-aus** [missionpinball/mpf#1304]
Getting the following error on mpf 0.52.0 and Python 3.7:

```
Process Process-1:
Traceback (most recent call last):
  File "/anaconda3/envs/mpf/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/anaconda3/envs/mpf/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/anaconda3/envs/mpf/lib/python3.7/site-packages/mpf/commands/both.py", line 14, in _start_mc
    module.Command(mpf_path, machine_path, args + ["--both"])
  File "/anaconda3/envs/mpf/lib/python3.7/site-packages/mpfmc/commands/mc.py", line 200, in __init__
    from mpfmc.core.mc import MpfMc
  File "/anaconda3/envs/mpf/lib/python3.7/site-packages/mpfmc/core/mc.py", line 38, in <module>
    from mpfmc.core.mode_controller import ModeController
  File "/anaconda3/envs/mpf/lib/python3.7/site-packages/mpfmc/core/mode_controller.py", line 9, in <module>
    from mpfmc.core.mode import Mode
  File "/anaconda3/envs/mpf/lib/python3.7/site-packages/mpfmc/core/mode.py", line 8, in <module>
    verbose=False)
TypeError: namedtuple() got an unexpected keyword argument 'verbose'
```

**Comment by jabdoa2** [comment]
fixed in avanwinkle's commit
