### ISSUE TITLE
Fix crash in high_score mode

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#1336]
```
Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\async_mode.py", line 39, in _done
    future.result()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\modes\high_score\code\high_score.py", line 151, in _run
    new_list.sort(key=lambda x: x[1], reverse=(not category_name in self.high_score_config['reverse_sort']))
KeyError: 'reverse_sort'
```

**Comment by jabdoa2** [comment]
Config cache problem. Fixed in https://github.com/missionpinball/mpf/commit/d806ceecb0a53e61d3726471008611b229fb4fd7
