### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by arthurlutz** [missionpinball/mpf#1411]
Sorry for the large debug log/traceback

```
mpf mc -X
kivy: Factory: 184 symbols loaded
kivy: Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
kivy: Video: Provider: null(['video_ffmpeg', 'video_ffpyplayer'] ignored)
kivy: Loading MPF-MC controller
mpfmc: Mission Pinball Framework Media Controller v0.52.5
mpfmc: Mission Pinball Framework Game Engine v0.52.6
mpfmc: Machine path: /home/arthur/local/mpf/mpf-examples/demo_man
ConfigProcessor: Config file in cache changed: /home/arthur/local/mpf/mpf-examples/demo_man/config/config
ConfigProcessor: Loading config from file /home/arthur/.virtualenvs/mpf/lib/python3.6/site-packages/mpfmc/mcconfig.yaml.
ConfigProcessor: Loading config: /home/arthur/.virtualenvs/mpf/lib/python3.6/site-packages/mpfmc/mcconfig.yaml
ConfigProcessor: Loading config from file /home/arthur/local/mpf/mpf-examples/demo_man/config/config.
ConfigProcessor: Loading config: /home/arthur/local/mpf/mpf-examples/demo_man/config/config
ConfigProcessor: Loading config: /home/arthur/local/mpf/mpf-examples/demo_man/config/hardware.yaml
ConfigProcessor: Loading config: /home/arthur/local/mpf/mpf-examples/demo_man/config/shots.yaml
ConfigProcessor: Loading config: /home/arthur/local/mpf/mpf-examples/demo_man/config/keyboard.yaml
ConfigProcessor: Config file cache created: /tmp/5895a58cfbb983a0485a19ae863cea7c.mpf_cache
mpfmc: Starting clock at 60.0Hz
EventManager: Duplicate handler for class {} on event init_phase_1 with priority 1. Handlers: [RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('d9077a36-92f7-44b0-ae50-e791b4561b14'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('e8c888d9-2c36-4094-a1b0-723586a4427a'), condition=None, blocking_facility=None)]
kivy: Text: Provider: sdl2
EventManager: Duplicate handler for class {} on event init_phase_1 with priority 1. Handlers: [RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('d9077a36-92f7-44b0-ae50-e791b4561b14'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('e8c888d9-2c36-4094-a1b0-723586a4427a'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('dce07684-b84c-470f-8ff7-e9458d0cafbf'), condition=None, blocking_facility=None)]
EventManager: Duplicate handler for class {} on event init_phase_1 with priority 1. Handlers: [RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('d9077a36-92f7-44b0-ae50-e791b4561b14'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('e8c888d9-2c36-4094-a1b0-723586a4427a'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('dce07684-b84c-470f-8ff7-e9458d0cafbf'), condition=None, blocking_facility=None)]
EventManager: Duplicate handler for class {} on event init_phase_1 with priority 1. Handlers: [RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('d9077a36-92f7-44b0-ae50-e791b4561b14'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('e8c888d9-2c36-4094-a1b0-723586a4427a'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('dce07684-b84c-470f-8ff7-e9458d0cafbf'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('1da40e35-6b74-44c7-8f5a-d848b3fc8b33'), condition=None, blocking_facility=None)]
EventManager: Duplicate handler for class {} on event init_phase_1 with priority 1. Handlers: [RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('d9077a36-92f7-44b0-ae50-e791b4561b14'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('e8c888d9-2c36-4094-a1b0-723586a4427a'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('dce07684-b84c-470f-8ff7-e9458d0cafbf'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('1da40e35-6b74-44c7-8f5a-d848b3fc8b33'), condition=None, blocking_facility=None)]
EventManager: Duplicate handler for class {} on event init_phase_1 with priority 1. Handlers: [RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('d9077a36-92f7-44b0-ae50-e791b4561b14'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('e8c888d9-2c36-4094-a1b0-723586a4427a'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('dce07684-b84c-470f-8ff7-e9458d0cafbf'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('1da40e35-6b74-44c7-8f5a-d848b3fc8b33'), condition=None, blocking_facility=None)]
EventManager: Duplicate handler for class {} on event init_phase_1 with priority 1. Handlers: [RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('d9077a36-92f7-44b0-ae50-e791b4561b14'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('e8c888d9-2c36-4094-a1b0-723586a4427a'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('dce07684-b84c-470f-8ff7-e9458d0cafbf'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('1da40e35-6b74-44c7-8f5a-d848b3fc8b33'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('39e6b184-49e0-4967-9d95-0dc7608a4d2f'), condition=None, blocking_facility=None)]
EventManager: Duplicate handler for class {} on event init_phase_1 with priority 1. Handlers: [RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('d9077a36-92f7-44b0-ae50-e791b4561b14'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('e8c888d9-2c36-4094-a1b0-723586a4427a'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('dce07684-b84c-470f-8ff7-e9458d0cafbf'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('1da40e35-6b74-44c7-8f5a-d848b3fc8b33'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('39e6b184-49e0-4967-9d95-0dc7608a4d2f'), condition=None, blocking_facility=None)]
EventManager: Duplicate handler for class {} on event init_phase_1 with priority 1. Handlers: [RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('d9077a36-92f7-44b0-ae50-e791b4561b14'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('e8c888d9-2c36-4094-a1b0-723586a4427a'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('dce07684-b84c-470f-8ff7-e9458d0cafbf'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('1da40e35-6b74-44c7-8f5a-d848b3fc8b33'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('39e6b184-49e0-4967-9d95-0dc7608a4d2f'), condition=None, blocking_facility=None)]
EventManager: Duplicate handler for class {} on event init_phase_1 with priority 1. Handlers: [RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('d9077a36-92f7-44b0-ae50-e791b4561b14'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('e8c888d9-2c36-4094-a1b0-723586a4427a'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('dce07684-b84c-470f-8ff7-e9458d0cafbf'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('1da40e35-6b74-44c7-8f5a-d848b3fc8b33'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('39e6b184-49e0-4967-9d95-0dc7608a4d2f'), condition=None, blocking_facility=None)]
EventManager: Duplicate handler for class {} on event init_phase_1 with priority 1. Handlers: [RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('d9077a36-92f7-44b0-ae50-e791b4561b14'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('e8c888d9-2c36-4094-a1b0-723586a4427a'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('dce07684-b84c-470f-8ff7-e9458d0cafbf'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('1da40e35-6b74-44c7-8f5a-d848b3fc8b33'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('39e6b184-49e0-4967-9d95-0dc7608a4d2f'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('12d262c7-7fc9-4a10-b1d5-81ad70a95b71'), condition=None, blocking_facility=None)]
EventManager: Duplicate handler for class {} on event init_phase_1 with priority 1. Handlers: [RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('d9077a36-92f7-44b0-ae50-e791b4561b14'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('e8c888d9-2c36-4094-a1b0-723586a4427a'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('dce07684-b84c-470f-8ff7-e9458d0cafbf'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('1da40e35-6b74-44c7-8f5a-d848b3fc8b33'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('39e6b184-49e0-4967-9d95-0dc7608a4d2f'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('12d262c7-7fc9-4a10-b1d5-81ad70a95b71'), condition=None, blocking_facility=None)]
EventManager: Duplicate handler for class {} on event init_phase_1 with priority 1. Handlers: [RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('d9077a36-92f7-44b0-ae50-e791b4561b14'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('e8c888d9-2c36-4094-a1b0-723586a4427a'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('dce07684-b84c-470f-8ff7-e9458d0cafbf'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('1da40e35-6b74-44c7-8f5a-d848b3fc8b33'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('39e6b184-49e0-4967-9d95-0dc7608a4d2f'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('12d262c7-7fc9-4a10-b1d5-81ad70a95b71'), condition=None, blocking_facility=None)]
EventManager: Duplicate handler for class {} on event init_phase_1 with priority 1. Handlers: [RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('d9077a36-92f7-44b0-ae50-e791b4561b14'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('e8c888d9-2c36-4094-a1b0-723586a4427a'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('dce07684-b84c-470f-8ff7-e9458d0cafbf'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('1da40e35-6b74-44c7-8f5a-d848b3fc8b33'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('39e6b184-49e0-4967-9d95-0dc7608a4d2f'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('12d262c7-7fc9-4a10-b1d5-81ad70a95b71'), condition=None, blocking_facility=None)]
EventManager: Duplicate handler for class {} on event init_phase_1 with priority 1. Handlers: [RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('d9077a36-92f7-44b0-ae50-e791b4561b14'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('e8c888d9-2c36-4094-a1b0-723586a4427a'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('dce07684-b84c-470f-8ff7-e9458d0cafbf'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('1da40e35-6b74-44c7-8f5a-d848b3fc8b33'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('39e6b184-49e0-4967-9d95-0dc7608a4d2f'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('12d262c7-7fc9-4a10-b1d5-81ad70a95b71'), condition=None, blocking_facility=None)]
EventManager: Duplicate handler for class {} on event init_phase_1 with priority 1. Handlers: [RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('d9077a36-92f7-44b0-ae50-e791b4561b14'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('e8c888d9-2c36-4094-a1b0-723586a4427a'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('dce07684-b84c-470f-8ff7-e9458d0cafbf'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('1da40e35-6b74-44c7-8f5a-d848b3fc8b33'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('39e6b184-49e0-4967-9d95-0dc7608a4d2f'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('12d262c7-7fc9-4a10-b1d5-81ad70a95b71'), condition=None, blocking_facility=None)]
EventManager: Duplicate handler for class {} on event init_phase_1 with priority 1. Handlers: [RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('d9077a36-92f7-44b0-ae50-e791b4561b14'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('e8c888d9-2c36-4094-a1b0-723586a4427a'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('dce07684-b84c-470f-8ff7-e9458d0cafbf'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('1da40e35-6b74-44c7-8f5a-d848b3fc8b33'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('39e6b184-49e0-4967-9d95-0dc7608a4d2f'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('12d262c7-7fc9-4a10-b1d5-81ad70a95b71'), condition=None, blocking_facility=None)]
EventManager: Duplicate handler for class {} on event init_phase_1 with priority 1. Handlers: [RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('d9077a36-92f7-44b0-ae50-e791b4561b14'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('e8c888d9-2c36-4094-a1b0-723586a4427a'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('dce07684-b84c-470f-8ff7-e9458d0cafbf'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('1da40e35-6b74-44c7-8f5a-d848b3fc8b33'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('39e6b184-49e0-4967-9d95-0dc7608a4d2f'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('12d262c7-7fc9-4a10-b1d5-81ad70a95b71'), condition=None, blocking_facility=None)]
EventManager: Duplicate handler for class {} on event init_phase_1 with priority 1. Handlers: [RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('d9077a36-92f7-44b0-ae50-e791b4561b14'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('e8c888d9-2c36-4094-a1b0-723586a4427a'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('dce07684-b84c-470f-8ff7-e9458d0cafbf'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('1da40e35-6b74-44c7-8f5a-d848b3fc8b33'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('39e6b184-49e0-4967-9d95-0dc7608a4d2f'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('12d262c7-7fc9-4a10-b1d5-81ad70a95b71'), condition=None, blocking_facility=None)]
EventManager: Duplicate handler for class {} on event init_phase_1 with priority 1. Handlers: [RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('d9077a36-92f7-44b0-ae50-e791b4561b14'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('e8c888d9-2c36-4094-a1b0-723586a4427a'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('dce07684-b84c-470f-8ff7-e9458d0cafbf'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('1da40e35-6b74-44c7-8f5a-d848b3fc8b33'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('39e6b184-49e0-4967-9d95-0dc7608a4d2f'), condition=None, blocking_facility=None), RegisteredHandler(callback=<bound method ConfigCollection.create_entries_from_root_config of {}>, priority=1, kwargs={}, key=UUID('12d262c7-7fc9-4a10-b1d5-81ad70a95b71'), condition=None, blocking_facility=None)]
kivy: Window: Provider: sdl2(['window_egl_rpi'] ignored)
kivy: GL: Using the "OpenGL" graphics system
kivy: GL: Backend used <sdl2>
kivy: GL: OpenGL version <b'4.6.0 NVIDIA 430.40'>
kivy: GL: OpenGL vendor <b'NVIDIA Corporation'>
kivy: GL: OpenGL renderer <b'GeForce GTX 1050/PCIe/SSE2'>
kivy: GL: OpenGL parsed version: 4, 6
kivy: GL: Shading version <b'4.60 NVIDIA'>
kivy: GL: Texture max size <32768>
kivy: GL: Texture max units <32>
kivy: Window: auto add sdl2 input provider
kivy: Window: virtual keyboard not allowed, single mode, not docked
AudioInterface: Initialized
kivy: Base: Start application main loop
EventManager: Event: ======'display_window_initialized'====== Args={}
EventManager: Event: ======'display_dmd_initialized'====== Args={}
mpfmc: Display: Setting 'dmd' as default display
kivy: Base: Leaving application in progress...
kivy: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/home/arthur/.virtualenvs/mpf/lib/python3.6/site-packages/mpfmc/commands/mc.py", line 209, in __init__
    thread_stopper=thread_stopper).run()
  File "/home/arthur/.virtualenvs/mpf/lib/python3.6/site-packages/kivy/app.py", line 855, in run
    runTouchApp()
  File "/home/arthur/.virtualenvs/mpf/lib/python3.6/site-packages/kivy/base.py", line 504, in runTouchApp
    EventLoop.window.mainloop()
  File "/home/arthur/.virtualenvs/mpf/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 747, in mainloop
    self._mainloop()
  File "/home/arthur/.virtualenvs/mpf/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 479, in _mainloop
    EventLoop.idle()
  File "/home/arthur/.virtualenvs/mpf/lib/python3.6/site-packages/kivy/base.py", line 339, in idle
    Clock.tick()
  File "/home/arthur/.virtualenvs/mpf/lib/python3.6/site-packages/kivy/clock.py", line 591, in tick
    self._process_events()
  File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
  File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
  File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
  File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
  File "/home/arthur/.virtualenvs/mpf/lib/python3.6/site-packages/mpfmc/uix/display.py", line 200, in _displays_initialized
    self.mc.displays_initialized()
  File "/home/arthur/.virtualenvs/mpf/lib/python3.6/site-packages/mpfmc/core/mc.py", line 314, in displays_initialized
    Window.initialize(self)
  File "/home/arthur/.virtualenvs/mpf/lib/python3.6/site-packages/mpfmc/uix/window.py", line 60, in initialize
    display_widget = DisplayWidget(mc, config=config)
  File "/home/arthur/.virtualenvs/mpf/lib/python3.6/site-packages/mpfmc/widgets/display.py", line 27, in __init__
    super().__init__(mc=mc, config=config, key=key)
  File "/home/arthur/.virtualenvs/mpf/lib/python3.6/site-packages/mpfmc/uix/widget.py", line 107, in __init__
    self._container = WidgetContainer(self, z=self.config['z'])
  File "/home/arthur/.virtualenvs/mpf/lib/python3.6/site-packages/mpfmc/uix/widget.py", line 953, in __init__
    super().__init__(size_hint=(1, 1))
  File "/home/arthur/.virtualenvs/mpf/lib/python3.6/site-packages/kivy/uix/relativelayout.py", line 265, in __init__
    super(RelativeLayout, self).__init__(**kw)
  File "/home/arthur/.virtualenvs/mpf/lib/python3.6/site-packages/kivy/uix/floatlayout.py", line 65, in __init__
    super(FloatLayout, self).__init__(**kwargs)
  File "/home/arthur/.virtualenvs/mpf/lib/python3.6/site-packages/kivy/uix/layout.py", line 76, in __init__
    super(Layout, self).__init__(**kwargs)
  File "/home/arthur/.virtualenvs/mpf/lib/python3.6/site-packages/kivy/uix/widget.py", line 361, in __init__
    rule_children=rule_children)
  File "/home/arthur/.virtualenvs/mpf/lib/python3.6/site-packages/kivy/uix/widget.py", line 469, in apply_class_lang_rules
    rule_children=rule_children)
  File "/home/arthur/.virtualenvs/mpf/lib/python3.6/site-packages/kivy/lang/builder.py", line 529, in apply
    trace('Lang: Found %d rules for %s' % (len(rules), widget))
  File "/home/arthur/.virtualenvs/mpf/lib/python3.6/site-packages/mpfmc/uix/widget.py", line 960, in __repr__
    return '<WidgetContainer id={} z={} key={}>'.format(self.id, self.z, self.key)
  File "kivy/properties.pyx", line 506, in kivy.properties.Property.__get__
  File "/home/arthur/.virtualenvs/mpf/lib/python3.6/site-packages/mpfmc/uix/widget.py", line 960, in __repr__
    return '<WidgetContainer id={} z={} key={}>'.format(self.id, self.z, self.key)

[snip]
  File "kivy/properties.pyx", line 506, in kivy.properties.Property.__get__
  File "/home/arthur/.virtualenvs/mpf/lib/python3.6/site-packages/mpfmc/uix/widget.py", line 960, in __repr__
    return '<WidgetContainer id={} z={} key={}>'.format(self.id, self.z, self.key)
  File "kivy/properties.pyx", line 506, in kivy.properties.Property.__get__
  File "/home/arthur/.virtualenvs/mpf/lib/python3.6/site-packages/mpfmc/uix/widget.py", line 960, in __repr__
    return '<WidgetContainer id={} z={} key={}>'.format(self.id, self.z, self.key)
  File "kivy/properties.pyx", line 506, in kivy.properties.Property.__get__
RecursionError: maximum recursion depth exceeded while calling a Python object
kivy: Stopping child threads... (1 remaining)
kivy: All child threads stopped.
```

**Comment by arthurlutz** [comment]
I forgot to say: a window pops up (black) and then closes.

**Comment by jabdoa2** [comment]
You probably have to downgrade kivy: https://groups.google.com/forum/m/#!topic/mpf-users/9zy3H575GfQ

**Comment by arthurlutz** [comment]
Thanks for the tip, I had tried but not far enough in the kivy history : 

```
pip  install cython
pip3 install kivy==1.10.1
```

Solved it.
