### ISSUE TITLE
Fix KeyError exception, config_player.py", line 183

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#165]
Fix this crash

```
[INFO              ] [Base        ] Leaving application in progress...
[ERROR             ] <Mode.char_doc>
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\mpfmc\commands\mc.py", line 129, in __init__
    machine_path=machine_path).run()
  File "c:\python34\lib\site-packages\kivy\app.py", line 828, in run
    runTouchApp()
  File "c:\python34\lib\site-packages\kivy\base.py", line 487, in runTouchApp
    EventLoop.window.mainloop()
  File "c:\python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "c:\python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "c:\python34\lib\site-packages\kivy\base.py", line 327, in idle
    Clock.tick()
  File "c:\python34\lib\site-packages\kivy\clock.py", line 515, in tick
    self._process_events()
  File "c:\python34\lib\site-packages\kivy\clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "c:\python34\lib\site-packages\kivy\clock.py", line 406, in tick
    ret = callback(self._dt)
  File "c:\python34\lib\site-packages\mpfmc\core\bcp_processor.py", line 96, in _get_from_queue
    self._process_command(cmd, **kwargs)
  File "c:\python34\lib\site-packages\mpfmc\core\bcp_processor.py", line 104, in _process_command
    self.bcp_commands[bcp_command](**kwargs)
  File "c:\python34\lib\site-packages\mpfmc\core\bcp_processor.py", line 153, in _bcp_mode_stop
    self.mc.modes[name].stop()
  File "c:\python34\lib\site-packages\mpfmc\core\mode.py", line 151, in stop
    item[0](item[1])
  File "c:\python34\lib\site-packages\mpf\core\config_player.py", line 183, in mode_stop
    event_keys = self.mode_keys.pop(mode)
KeyError: <Mode.char_doc>
Press ENTER to close this window...
```

**Comment by toomanybrians** [comment]
fixed
