### ISSUE TITLE
Make a better error instead of this show crash

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#193]
Figure out why this crash happened, and turn it into a better error instead of crashing.

Note from Alexander about this: "OK. I have a profile: in a group in my config. But not in my base mode. In base I add the rotate left/right. And then it crashes."

```
ERROR : root : list index out of range
Traceback (most recent call last):
 File "/home/pi/mpf/mpf/commands/core.py", line 130, in __init__
   MachineController(mpf_path, machine_path, vars(args)).run()
 File "/home/pi/mpf/mpf/core/machine.py", line 554, in run
   self._run_loop()
 File "/home/pi/mpf/mpf/core/machine.py", line 575, in _run_loop
   self.process_frame()
 File "/home/pi/mpf/mpf/core/machine.py", line 590, in process_frame
   self.events.process_event_queue()
 File "/home/pi/mpf/mpf/core/events.py", line 477, in process_event_queue
   **event[3])
 File "/home/pi/mpf/mpf/core/events.py", line 412, in _process_event
   result = handler[0](**merged_kwargs)
 File "/home/pi/mpf/mpf/core/mode.py", line 412, in _control_event_handler
   callback(mode=self)
 File "/home/pi/mpf/mpf/devices/shot_group.py", line 277, in rotate_right
   self.rotate(direction='right', mode=mode)
 File "/home/pi/mpf/mpf/devices/shot_group.py", line 266, in rotate
   show_step=shot_state_list[i][1])
 File "/home/pi/mpf/mpf/devices/shot.py", line 587, in jump
   self._update_show(show_step=show_step)
 File "/home/pi/mpf/mpf/devices/shot.py", line 268, in _update_show
   self.running_show.advance(show_step=show_step)
 File "/home/pi/mpf/mpf/assets/show.py", line 502, in advance
   self._run_next_step()
 File "/home/pi/mpf/mpf/assets/show.py", line 514, in _run_next_step
   iter(self.show_steps[self.next_step_index].items())):
```

**Comment by toomanybrians** [comment]
fixed
