### ISSUE TITLE
Why did these opp tests fail?

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#350]
A user had these two failures, win10, x64

```
======================================================================
FAIL: test_opp (mpf.tests.test_OPP.TestOPP)
----------------------------------------------------------------------
Traceback (most recent call last):
 File "C:\Python34\lib\site-packages\mpf\tests\test_OPP.py", line 121, in test_opp
   self._test_flippers()
 File "C:\Python34\lib\site-packages\mpf\tests\test_OPP.py", line 251, in _test_flippers
   self.assertFalse(self.serialMock.expected_commands)
AssertionError: {b' \x14\x03\x01\n\x06\xe8\xff': False} is not false

======================================================================
FAIL: test_opp (mpf.tests.test_OPP.TestOPP)
----------------------------------------------------------------------
Traceback (most recent call last):
 File "C:\Python34\lib\site-packages\mpf\tests\test_OPP.py", line 94, in tearDown
   self.assertFalse(self.serialMock.crashed)
AssertionError: True is not false

----------------------------------------------------------------------
Ran 463 tests in 15.317s

FAILED (failures=2)
```

**Comment by jabdoa2** [comment]
Cannot reproduce unfortunately

**Comment by jabdoa2** [comment]
Due to timing OPP could send a command twice if no context switch happened in between. Fixed this by making this time independent.
