### ISSUE TITLE
Mode Timer Crash

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#373]
Reported by user:

```
INFO : Mode.game : Mode Starting. Priority: 20
INFO : Mode.kickback : Mode Starting. Priority: 200
ERROR : root : 'NoneType' object does not support item assignment
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/mpf/commands/game.py", line 130, in __init__
    MachineController(mpf_path, machine_path, vars(args)).run()
  File "/usr/local/lib/python3.4/dist-packages/mpf/core/machine.py", line 540, in run
    self._run_loop()
  File "/usr/local/lib/python3.4/dist-packages/mpf/core/machine.py", line 563, in _run_loop
    self.process_frame()
  File "/usr/local/lib/python3.4/dist-packages/mpf/core/machine.py", line 578, in process_frame
    self.events.process_event_queue()
  File "/usr/local/lib/python3.4/dist-packages/mpf/core/events.py", line 481, in process_event_queue
    **event[3])
  File "/usr/local/lib/python3.4/dist-packages/mpf/core/events.py", line 416, in _process_event
    result = handler[0](**merged_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/mpf/core/mode.py", line 190, in start
    self._setup_timers()
  File "/usr/local/lib/python3.4/dist-packages/mpf/core/mode.py", line 509, in _setup_timers
    name=timer, config=settings)
  File "/usr/local/lib/python3.4/dist-packages/mpf/core/mode_timer.py", line 26, in __init__
    self.mode.player[self.tick_var] = 0
TypeError: 'NoneType' object does not support item assignment

```

**Comment by jabdoa2** [comment]
Game and Kickback mode start at the same time. Player is not initialised when kickback starts. We probably have to move _setup_timers to _started in mode. Need to add test.
