### ISSUE TITLE
Crash when asset file does not exist but is specified in config

### ISSUE THREAD

**Issue by qcapen** [missionpinball/mpf#473]
MPF will crash if an asset is specified in a config file but the asset file does not exist.  Found this bug due to missing power_off.ogg sound asset file from the service mode when running demo man.

Here is the log from the MC where the crash occurs:

2016-09-11 21:29:12,892 : DEBUG : AssetManager : Processing assets from base folder: C:\Python34\lib\site-packages\mpf-0.31.0.dev263-py3.4.egg\mpf\modes\service\sounds
2016-09-11 21:29:12,892 : INFO : kivy : Base: Leaving application in progress...
2016-09-11 21:29:12,893 : ERROR : kivy : 'file'
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\mpf_mc-0.31.0.dev17-py3.4-win-amd64.egg\mpfmc\commands\mc.py", line 153, in **init**
    thread_stopper=thread_stopper).run()
  File "C:\Python34\lib\site-packages\kivy\app.py", line 828, in run
    runTouchApp()
  File "C:\Python34\lib\site-packages\kivy\base.py", line 487, in runTouchApp
    EventLoop.window.mainloop()
  File "C:\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "C:\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "C:\Python34\lib\site-packages\kivy\base.py", line 327, in idle
    Clock.tick()
  File "C:\Python34\lib\site-packages\kivy\clock.py", line 515, in tick
    self._process_events()
  File "C:\Python34\lib\site-packages\kivy\clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "C:\Python34\lib\site-packages\kivy\clock.py", line 406, in tick
    ret = callback(self._dt)
  File "C:\Python34\lib\site-packages\mpf_mc-0.31.0.dev17-py3.4-win-amd64.egg\mpfmc\uix\display.py", line 122, in _displays_initialized
    self.mc.displays_initialized()
  File "C:\Python34\lib\site-packages\mpf_mc-0.31.0.dev17-py3.4-win-amd64.egg\mpfmc\core\mc.py", line 222, in displays_initialized
    self._init()
  File "C:\Python34\lib\site-packages\mpf_mc-0.31.0.dev17-py3.4-win-amd64.egg\mpfmc\core\mc.py", line 265, in _init
    self.events.process_event_queue()
  File "C:\Python34\lib\site-packages\mpf-0.31.0.dev263-py3.4.egg\mpf\core\events.py", line 502, in process_event_queue
    **event[3])
  File "C:\Python34\lib\site-packages\mpf-0.31.0.dev263-py3.4.egg\mpf\core\events.py", line 438, in _process_event
    result = handler.callback(**merged_kwargs)
  File "C:\Python34\lib\site-packages\mpf-0.31.0.dev263-py3.4.egg\mpf\core\assets.py", line 177, in _create_assets
    self._create_assets_from_disk(config=mode.config, mode=mode)
  File "C:\Python34\lib\site-packages\mpf-0.31.0.dev263-py3.4.egg\mpf\core\assets.py", line 285, in _create_assets_from_disk
    file=config[ac['disk_asset_section']][asset]['file'],
KeyError: 'file'
2016-09-11 21:29:12,899 : INFO : kivy : Stopping child threads... (1 remaining)
2016-09-11 21:29:13,603 : INFO : kivy : All child threads stopped.

A much better error message would help the user determine what happened.  I think it is fine to throw an exception that causes MPF to stop, however a clear message is needed so the problem can be resolved.

**Comment by qcapen** [comment]
Fixed this particular instance of this bug.  However the root cause still remains.  Not a big enough deal to fix in 0.31, but should be addressed with a better error message in 0.32.

**Comment by qcapen** [comment]
Better error message added in 0.33.  Closing this issue.
