### ISSUE TITLE
crash on adding widgets

### ISSUE THREAD

**Issue by MarkInc666** [missionpinball/mpf#553]
File "c:\python34\lib\site-packages\mpfmc\uix\slide.py", line 145, in add_widgets_from_config
    mc=self.mc, config=widget, slide=self, key=this_key, play_kwargs=play_kwargs)

Works when you remove the slide parameter on line 145.

'''2016-09-23 10:23:02,503 : DEBUG : Events : Registered McWidgetPlayer._add_widget_to_slide_when_active as a handler for 'slide_none_created', priority: 1, kwargs: {'widget': 'player_number', 's': {'slide': None, 'key': 'game-player_number', 'target': None}, 'play_kwargs': {}, 'slide_name': None}
2016-09-23 10:23:02,504 : DEBUG : Events : Registered Text._player_var_change as a handler for 'player_player|number', priority: 1, kwargs: {}
2016-09-23 10:23:02,504 : DEBUG : Events : Registered Text._player_var_change as a handler for 'player_turn_start', priority: 1, kwargs: {}
2016-09-23 10:23:02,505 : DEBUG : Events : Registered McWidgetPlayer._add_widget_to_slide_when_active as a handler for 'slide_none_created', priority: 1, kwargs: {'widget': 'left_frame', 's': {'slide': None, 'key': 'game-left_frame', 'target': None}, 'play_kwargs': {}, 'slide_name': None}
2016-09-23 10:23:02,505 : INFO : kivy : Base: Leaving application in progress...
2016-09-23 10:23:02,505 : ERROR : kivy : __init__() got an unexpected keyword argument 'slide'
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\mpfmc\commands\mc.py", line 153, in **init**
    thread_stopper=thread_stopper).run()
  File "c:\python34\lib\site-packages\kivy\app.py", line 828, in run
    runTouchApp()
  File "c:\python34\lib\site-packages\kivy\base.py", line 487, in runTouchApp
    EventLoop.window.mainloop()
  File "c:\python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "c:\python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "c:\python34\lib\site-packages\kivy\base.py", line 327, in idle
    Clock.tick()
  File "c:\python34\lib\site-packages\kivy\clock.py", line 515, in tick
    self._process_events()
  File "c:\python34\lib\site-packages\kivy\clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "c:\python34\lib\site-packages\kivy\clock.py", line 406, in tick
    ret = callback(self._dt)
  File "c:\python34\lib\site-packages\mpfmc\core\mc.py", line 391, in tick
    self.events.process_event_queue()
  File "c:\python34\lib\site-packages\mpf\core\events.py", line 502, in process_event_queue
    **event[3])
  File "c:\python34\lib\site-packages\mpf\core\events.py", line 438, in _process_event
    result = handler.callback(**merged_kwargs)
  File "c:\python34\lib\site-packages\mpf\core\config_player.py", line 230, in config_play_callback
    self.play(settings=settings, context=context, priority=priority, *_kwargs)
  File "c:\python34\lib\site-packages\mpfmc\config_players\widget_player.py", line 155, in play
    self._action_add(s, instance_dict, widget, context, kwargs)
  File "c:\python34\lib\site-packages\mpfmc\config_players\widget_player.py", line 113, in _action_add
    slide.add_widgets_from_library(name=widget, play_kwargs=play_kwargs, *_s)
  File "c:\python34\lib\site-packages\mpfmc\uix\slide.py", line 110, in add_widgets_from_library
    play_kwargs=play_kwargs)
  File "c:\python34\lib\site-packages\mpfmc\uix\slide.py", line 145, in add_widgets_from_config
    mc=self.mc, config=widget, slide=self, key=this_key, play_kwargs=play_kwargs)
TypeError: __init__() got an unexpected keyword argument 'slide'
2016-09-23 10:23:02,517 : DEBUG : MPF-MC BCP Server : Received "mode_start?priority=int:1200&name=shot_multiplier"
2016-09-23 10:23:02,518 : INFO : kivy : Stopping child threads... (3 remaining)
2016-09-23 10:23:02,523 : DEBUG : MPF-MC BCP Server : Received "mode_start?priority=int:950&name=combos"
2016-09-23 10:23:02,524 : INFO : mpfmc : Stopping...

**Comment by toomanybrians** [comment]
Fixed in 0.31.4
