### ISSUE TITLE
Random test crash mpf.tests.test_Tilt.TestTilt.test_tilt_event

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#642]
Very very rare: https://ci.appveyor.com/project/toomanybrians/mpf/build/1.0.1777/job/9ycaaupvqy9okfpx

```
======================================================================
ERROR: test_tilt_event (mpf.tests.test_Tilt.TestTilt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\projects\mpf\mpf\tests\MpfTestCase.py", line 152, in advance_time_and_run
    self.loop.run_until_complete(asyncio.sleep(delay=delta, loop=self.loop))
  File "C:\Python34-x64\lib\asyncio\base_events.py", line 335, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "c:\projects\mpf\mpf\tests\test_Tilt.py", line 97, in test_tilt_event
    self.advance_time_and_run(1)
  File "c:\projects\mpf\mpf\tests\MpfTestCase.py", line 156, in advance_time_and_run
    raise self._exception['exception']
KeyError: 'exception'
----------------------------------------------------------------------

```

**Comment by jabdoa2** [comment]
fixed in dev
