### ISSUE TITLE
Crash in MPF related to Achievements

### ISSUE THREAD

**Issue by GabeKnuth** [missionpinball/mpf#661]
I'm not sure if this is an MPF thing or a BND thing, but I get a crash when all the main 5 modes are completed in BND (Jukebox, World Tour, etc...). As soon as the fifth one is done, the crash happens. Verbose log attached.
[2016-10-27-21-43-41-mpf-DESKTOP-QBFID3T.log.zip](https://github.com/missionpinball/mpf/files/557588/2016-10-27-21-43-41-mpf-DESKTOP-QBFID3T.log.zip)

**Comment by jabdoa2** [comment]
Actual error from log:

```
2016-10-27 21:47:58,374 : ERROR : asyncio : Exception in callback EventManager.process_event_queue()
handle: <Handle EventManager.process_event_queue()>
Traceback (most recent call last):
  File "c:\python34\lib\random.py", line 253, in choice
    i = self._randbelow(len(seq))
  File "c:\python34\lib\random.py", line 230, in _randbelow
    r = getrandbits(k)          # 0 <= r < 2**k
ValueError: number of bits must be greater than zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python34\lib\asyncio\events.py", line 125, in _run
    self._callback(*self._args)
  File "f:\mpf\mpf\core\events.py", line 574, in process_event_queue
    **event[3])
  File "f:\mpf\mpf\core\events.py", line 542, in _process_event
    result = self._run_handlers(event, ev_type, kwargs)
  File "f:\mpf\mpf\core\events.py", line 499, in _run_handlers
    result = handler.callback(**merged_kwargs)
  File "f:\mpf\mpf\core\mode.py", line 487, in _control_event_handler
    callback(mode=self)
  File "f:\mpf\mpf\devices\achievement_group.py", line 55, in enable
    self._get_current().select()
  File "f:\mpf\mpf\devices\achievement_group.py", line 79, in _get_current
    self._selected = choice(self._get_available_achievements())
  File "c:\python34\lib\random.py", line 255, in choice
    raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence
2016-10-27 21:47:58,384 : ERROR : root : Cannot choose from an empty sequence
Traceback (most recent call last):
  File "c:\python34\lib\random.py", line 253, in choice
    i = self._randbelow(len(seq))
  File "c:\python34\lib\random.py", line 230, in _randbelow
    r = getrandbits(k)          # 0 <= r < 2**k
ValueError: number of bits must be greater than zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:\mpf\mpf\commands\game.py", line 140, in __init__
    MachineController(mpf_path, machine_path, vars(args)).run()
  File "f:\mpf\mpf\core\machine.py", line 565, in run
    self._run_loop()
  File "f:\mpf\mpf\core\machine.py", line 606, in _run_loop
    raise self._exception['exception']
  File "c:\python34\lib\asyncio\events.py", line 125, in _run
    self._callback(*self._args)
  File "f:\mpf\mpf\core\events.py", line 574, in process_event_queue
    **event[3])
  File "f:\mpf\mpf\core\events.py", line 542, in _process_event
    result = self._run_handlers(event, ev_type, kwargs)
  File "f:\mpf\mpf\core\events.py", line 499, in _run_handlers
    result = handler.callback(**merged_kwargs)
  File "f:\mpf\mpf\core\mode.py", line 487, in _control_event_handler
    callback(mode=self)
  File "f:\mpf\mpf\devices\achievement_group.py", line 55, in enable
    self._get_current().select()
  File "f:\mpf\mpf\devices\achievement_group.py", line 79, in _get_current
    self._selected = choice(self._get_available_achievements())
  File "c:\python34\lib\random.py", line 255, in choice
    raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence
```
