### ISSUE TITLE
Crash when using monitor with event viewer

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#682]
```
ERROR : asyncio : Exception in callback EventManager.process_event_queue()
handle: <Handle EventManager.process_event_queue()>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/core/events.py", line 581, in process_event_queue
    callback(**kwargs)
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/core/mode.py", line 248, in _started
    callback=self._mode_started_callback)
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/core/events.py", line 298, in post
    self._post(event, ev_type=None, callback=callback, **kwargs)
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/core/events.py", line 415, in _post
    self.machine.bcp.interface.monitor_posted_event(posted_event)
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/core/bcp/bcp_interface.py", line 118, in monitor_posted_event
    self.machine.events.registered_handlers.get(posted_event.event, []))
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/core/bcp/bcp_transport.py", line 95, in send_to_clients_with_handler
    self.send_to_clients(clients, bcp_command, **kwargs)
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/core/bcp/bcp_transport.py", line 90, in send_to_clients
    self.send_to_client(client, bcp_command, **kwargs)
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/core/bcp/bcp_transport.py", line 100, in send_to_client
    client.send(bcp_command, kwargs)
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/core/bcp/bcp_socket_client.py", line 205, in send
    bcp_string = encode_command_string(bcp_command, **bcp_command_args)
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/core/bcp/bcp_socket_client.py", line 116, in encode_command_string
    kwarg_string = 'json={}'.format(json.dumps(kwargs, cls=MpfJSONEncoder))
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be a string
```

**Comment by jabdoa2** [comment]
fix in dev
