### ISSUE TITLE
Score Player Crash

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#831]
Found by afl
```
Traceback (most recent call last):
  File "afl_fuzz.py", line 120, in <module>
    runner.run(action_str)
  File "afl_fuzz.py", line 95, in run
    self.advance_time_and_run(ms / 1000.0)
  File "afl_fuzz.py", line 66, in advance_time_and_run
    raise self._exception['exception']
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/core/events.py", line 655, in process_event_queue
    **event[3])
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/core/events.py", line 624, in _process_event
    result = self._run_handlers(event, ev_type, kwargs)
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/core/events.py", line 583, in _run_handlers
    result = handler.callback(**merged_kwargs)
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/core/config_player.py", line 270, in config_play_callback
    self.play(settings=settings, context=context, calling_context=calling_context, priority=priority, **kwargs)
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/config_players/score_player.py", line 28, in play
    self._score(var, s)
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/config_players/score_player.py", line 40, in _score
    self.machine.game.player[var] += entry['score'].evaluate([])
AttributeError: 'NoneType' object has no attribute 'player'

```

**Comment by jabdoa2** [comment]
symptom of #838

**Comment by jabdoa2** [comment]
fixed in dev
