### ISSUE TITLE
Ball Device Lost Ball Crash

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#834]
```
Received eject failed. Eject lost ball.
WARNING: Path is not going to ball_missing_target <playfield.playfield_front>. Restoring path by requesting new ball to target <ball_device.bd_launcher_front>.
WARNING: Received duplicate switch state, which means this switch had some non-debounced state changes. This could be nothing, but if it happens a lot it could indicate noise or interference on the line. Switch: s_center_ramp_success_front
Received eject failed. Eject lost ball.
WARNING: Path to <ball_device.bd_feeder_back> canceled. Assuming the ball jumped to <playfield.playfield_back>.
Traceback (most recent call last):
  File "/home/jan/cloud/flipper/src/mpf/tools/afl_fuzz.py", line 62, in advance_time_and_run
    self.loop.run_until_complete(asyncio.sleep(delay=delta, loop=self.loop))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 385, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jan/cloud/flipper/src/mpf/tools/afl_fuzz.py", line 120, in <module>
    runner.run(action_str)
  File "/home/jan/cloud/flipper/src/mpf/tools/afl_fuzz.py", line 95, in run
    self.advance_time_and_run(ms / 1000.0)
  File "/home/jan/cloud/flipper/src/mpf/tools/afl_fuzz.py", line 66, in advance_time_and_run
    raise self._exception['exception']
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/devices/ball_device/ball_count_handler.py", line 194, in wait_for_ball
    yield from self.ball_device.incoming_balls_handler.ball_arrived()
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/devices/ball_device/incoming_balls_handler.py", line 189, in ball_arrived
    yield from self.ball_device.unexpected_ball_received()
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/devices/ball_device/ball_device.py", line 155, in unexpected_ball_received
    self._balls_added_callback(1, unclaimed_balls)
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/devices/ball_device/ball_device.py", line 469, in _balls_added_callback
    self.setup_eject_chain(path, not self.config['auto_fire_on_unexpected_ball'])
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/devices/ball_device/ball_device.py", line 585, in setup_eject_chain
    .format(self.name, path))
AssertionError: Tried to setup an eject chain, but there are no available balls. Device: bd_launcher_front, Path: deque([<ball_device.bd_launcher_front>, <ball_device.bd_trough_back>, <ball_device.bd_launcher_back>, <ball_device.bd_feeder_front>, <playfield.playfield_front>])

```

Fuzzer input:
ff7fffffffff362666e96400fa323232b2323232323f1e5d000206192e2c
fc1dab20381e1a1cffffff7f86368032260000263f26ffffffff00fa3232
32260000f71a1a1a12011a2666fa6400fa323200b2323232323f1e3a0002
00007ffffc206400fa323232b232b232323f1e3a000206032e32fc341720
382038093c021a1a1a1a1a011a1a1a1ae92b56461e3ae80386726487

**Comment by jabdoa2** [comment]
Similar problem:
```
Received eject failed. Eject lost ball.
WARNING: Path is not going to ball_missing_target <playfield.playfield_front>. Restoring path by requesting new ball to target <ball_device.bd_feeder_front>.
WARNING: Received duplicate switch state, which means this switch had some non-debounced state changes. This could be nothing, but if it happens a lot it could indicate noise or interference on the line. Switch: s_center_ramp_success_front
Traceback (most recent call last):
  File "/home/jan/cloud/flipper/src/mpf/tools/afl_fuzz.py", line 62, in advance_time_and_run
    self.loop.run_until_complete(asyncio.sleep(delay=delta, loop=self.loop))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 385, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jan/cloud/flipper/src/mpf/tools/afl_fuzz.py", line 120, in <module>
    runner.run(action_str)
  File "/home/jan/cloud/flipper/src/mpf/tools/afl_fuzz.py", line 95, in run
    self.advance_time_and_run(ms / 1000.0)
  File "/home/jan/cloud/flipper/src/mpf/tools/afl_fuzz.py", line 66, in advance_time_and_run
    raise self._exception['exception']
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/devices/ball_device/ball_device_state_handler.py", line 41, in _done
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/devices/ball_device/ball_count_handler.py", line 270, in _run
    yield from self.ball_device.incoming_balls_handler.ball_arrived()
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/devices/ball_device/incoming_balls_handler.py", line 189, in ball_arrived
    yield from self.ball_device.unexpected_ball_received()
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/devices/ball_device/ball_device.py", line 155, in unexpected_ball_received
    self._balls_added_callback(1, unclaimed_balls)
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/devices/ball_device/ball_device.py", line 469, in _balls_added_callback
    self.setup_eject_chain(path, not self.config['auto_fire_on_unexpected_ball'])
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/devices/ball_device/ball_device.py", line 585, in setup_eject_chain
    .format(self.name, path))
AssertionError: Tried to setup an eject chain, but there are no available balls. Device: bd_feeder_front, Path: deque([<ball_device.bd_feeder_front>, <playfield.playfield_front>])

```

Fuzzer input:
ff7f20f8021e20301e1a1cfa32106497323232323f1e3a000100007feffc
e964005d323232c600007fff1e1a1cfa321032b2323232323f1e32030000
0010323f1e3a08db05033e2cfc1d0000007fff323f0d39eb3f763232323f
1e3200203ae821301e1a1cfa321032b27f3232323f1e32106a726487

**Comment by jabdoa2** [comment]
Fix in https://github.com/missionpinball/mpf/commit/a6c15dd0142ae1165752c33cbea24416c3d4204b.

Write two testcases:
1. Ball lost but no other ball available -> Should trigger this crash
2. Ball lost and no path (currently untested)

**Comment by jabdoa2** [comment]
fixed in next

**Comment by jabdoa2** [comment]
crash fixed in dev. test seems to require looping ball devices
