### ISSUE TITLE
Extra ball crash

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#874]
2017-04-16 21:55:56,350 : Mode.attract : Stopped.
2017-04-16 21:55:56,352 : EventManager : Event: ======'mode_attract_stopped'====== Args={}
2017-04-16 21:55:56,353 : EventManager : Event: ======'clear'====== Args={'key': 'attract'}
2017-04-16 21:55:56,353 : Mode.game : Started. Priority: 20
2017-04-16 21:55:56,354 : EventManager : Event: ======'mode_game_started'====== Args={}
2017-04-16 21:55:56,356 : EventManager : Event: ======'game_starting'====== Args={'game': <Mode.game>}
2017-04-16 21:55:56,380 : Machine : Shutting down...
2017-04-16 21:55:56,380 : EventManager : Event: ======'shutdown'====== Args={}
2017-04-16 21:55:56,385 : Machine : Shutting down...
2017-04-16 21:55:56,385 : EventManager : Event: ======'shutdown'====== Args={}
2017-04-16 21:55:56,391 : asyncio : Exception in callback EventManager._done(<Task finishe...s_awarded'",)>)
handle: <Handle EventManager._done(<Task finishe...s_awarded'",)>)>
Traceback (most recent call last):
  File "c:\python34\lib\asyncio\events.py", line 125, in _run
    self._callback(*self._args)
  File "c:\python34\lib\site-packages\mpf\core\events.py", line 572, in _done
    future.result()
  File "c:\python34\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "c:\python34\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "c:\python34\lib\site-packages\mpf\core\events.py", line 507, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "c:\python34\lib\site-packages\mpf\core\mode.py", line 196, in start
    self._add_mode_devices()
  File "c:\python34\lib\site-packages\mpf\core\mode.py", line 384, in _add_mode_devices
    player=self.player)
  File "c:\python34\lib\site-packages\mpf\devices\extra_ball.py", line 69, in device_added_to_mode
    if self.name not in self.player.extra_balls_awarded:
AttributeError: 'NoneType' object has no attribute 'extra_balls_awarded'
2017-04-16 21:55:56,400 : root : 'NoneType' object has no attribute 'extra_balls_awarded'
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\mpf\commands\game.py", line 165, in __init__
    MachineController(mpf_path, machine_path, vars(args)).run()
  File "c:\python34\lib\site-packages\mpf\core\machine.py", line 636, in run
    self._run_loop()
  File "c:\python34\lib\site-packages\mpf\core\machine.py", line 677, in _run_loop
    raise self._exception['exception']
  File "c:\python34\lib\asyncio\events.py", line 125, in _run
    self._callback(*self._args)
  File "c:\python34\lib\site-packages\mpf\core\events.py", line 572, in _done
    future.result()
  File "c:\python34\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "c:\python34\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "c:\python34\lib\site-packages\mpf\core\events.py", line 507, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "c:\python34\lib\site-packages\mpf\core\mode.py", line 196, in start
    self._add_mode_devices()
  File "c:\python34\lib\site-packages\mpf\core\mode.py", line 384, in _add_mode_devices
    player=self.player)
  File "c:\python34\lib\site-packages\mpf\devices\extra_ball.py", line 69, in device_added_to_mode
    if self.name not in self.player.extra_balls_awarded:
AttributeError: 'NoneType' object has no attribute 'extra_balls_awarded'

**Comment by jabdoa2** [comment]
From: https://groups.google.com/forum/m/#!topic/mpf-users/e-wo1bfF1E4
