### ISSUE TITLE
pyserial-asyncio error

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#951]
```
asyncio : Unhandled error in exception handler
context: {'transport': SerialTransport(<_UnixSelectorEventLoop running=True closed=False debug=False>, <asyncio.streams.StreamReaderProtocol object at 0x7fc746514b00>, Serial<id=0x7fc74643fda0, open=True>(port='/dev/ttyUSB0', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=0, xonxoff=False, rtscts=False, dsrdtr=False)), 'exception': SerialTimeoutException('Write timeout',), 'protocol': <asyncio.streams.StreamReaderProtocol object at 0x7fc746514b00>, 'message': 'Fatal write error on serial transport'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/serial/serialposix.py", line 534, in write
    n = os.write(self.fd, d)
BlockingIOError: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/jan/cloud/flipper/src/pyserial-asyncio/serial_asyncio/__init__.py", line 120, in write
    n = self._serial.write(data)
  File "/usr/local/lib/python3.5/dist-packages/serial/serialposix.py", line 568, in write
    raise writeTimeoutError
serial.serialutil.SerialTimeoutException: Write timeout

```

**Comment by jabdoa2** [comment]
Waiting on upstream to have this permanently fixed

**Comment by jabdoa2** [comment]
Merged upstream. Waiting for pyserial release
